# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 20:04
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_wallet'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('members', django.db.models.manager.Manager()),
            ],
        ),
    ]
