# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20161017_2004'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='payment',
            managers=[
            ],
        ),
    ]
