# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 20:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='members',
            field=models.ManyToManyField(through='wallet.Balance', to=settings.AUTH_USER_MODEL),
        ),
    ]
