# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 18:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20161018_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='time_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 18, 18, 15, 33, 189399)),
            preserve_default=False,
        ),
    ]
